### ISSUE TITLE
HTML5 App is not visible in SaaS consumer subaccount

### ISSUE THREAD

**Issue by miyasuta** [SAP-samples/btp-developer-guide-cap#116]
## Background
I am following the tutorial : [Implement Multitenancy in a Full-Stack CAP Application Following SAP BTP Developer’s Guide](https://github.com/SAP-samples/btp-developer-guide-cap/tree/main/documentation/saas), and I am now at the last step: [Subscribe to the Application](https://github.com/SAP-samples/btp-developer-guide-cap/blob/main/documentation/saas/5-subscribe.md).
I have created a new consumer subaccount in the same region as the provider subaccount. 

## Issue
Although the subscription was successful, the HTML5 application is not visible from the consumer subaccount.
![image](https://github.com/user-attachments/assets/99e5b4d8-5051-44f8-bb70-8ea2f1ac374b)

![image](https://github.com/user-attachments/assets/f5ccc69e-c60b-48ac-bc5e-51af2cb2e035)

I have configured destinations, and the tile is visible in the consumer's Work Zone site.
![image](https://github.com/user-attachments/assets/5db5669c-b4b1-490b-81f2-23aeb3f13fbe)

However, when I press the tile, the app keeps loading, and I see that fetching ui5AppInfo.json is failing with a 404 error.
![image](https://github.com/user-attachments/assets/9505f022-1694-4774-97a3-825c0a004123)

The dependency viewer shows the following status.
![image](https://github.com/user-attachments/assets/a80cb205-6bbf-4dd4-86be-32a292457696)

Any suggestions on what might be missing?

The source code is uploaded to the following repository in the "multitenancy" branch.
https://github.com/miyasuta/incident-management-2410/tree/multitenancy

**Comment by gopalanand333** [comment]
@miyasuta 
Can you check if your application is visible in the provider account's html5 apps section? Also steps can be validated using this tutorial : https://developers.sap.com/tutorials/integrate-with-work-zone.html

**Comment by miyasuta** [comment]
@gopalanand333 
Thank you for your reply. The application is visible in the provider subaccount. Also, when I subscribed to the SaaS app in the provider subaccount, the app could be launched in SAP Build Work Zone without any issues.
![image](https://github.com/user-attachments/assets/9ab59554-ee05-45ef-b610-29f20cd90594)

**Comment by gopalanand333** [comment]
@miyasuta 
I see that your tenant mode is set to dedicated
```
  - name: incident-management-2410-auth
    type: org.cloudfoundry.managed-service
    parameters:
      config:
        tenant-mode: **dedicated**
        xsappname: incident-management-2410-${org}-${space}
      path: ./xs-security.json
      service: xsuaa
      service-plan: application
```
For multitenancy we would need **shared** mode

**Comment by miyasuta** [comment]
@gopalanand333 
Thank you for your reply.
I have updated the tenant-mode to **shared**, undeployed and redeployed the application. However, I am still not seeing the app in HTML5 Apps section of the consumer subaccount.
![image](https://github.com/user-attachments/assets/073c6b26-4818-4b27-b6f0-4bbedb89f0c7)

I suspect that the **mtx/sidecar/package.json** settings might be incorrect. Could you check the settings below?
```
  "cds": {
    "profile": "mtx-sidecar",
    "requires": {
      "html5-repo": {
        "vcap": {
          "label": "html5-apps-repo",
          "plan": "app-host"
        },
        "subscriptionDependency": {
          "uaa": "xsappname"
        }
      }
    }
  }
```

**Comment by miyasuta** [comment]
@gopalanand333 
I've corrected the package.json. According to the [instruction](https://github.com/SAP-samples/btp-developer-guide-cap/blob/main/documentation/saas/enable-mtx/5-add-dependent-services.md), we need "html5-host", not "html5-repo".  But I am still having the same issue.
```
  "cds": {
    "profile": "mtx-sidecar",
    "requires": {
      "html5-host": { 
        "vcap": {
          "label": "html5-apps-repo",
          "plan": "app-host"
        },
        "subscriptionDependency": {
          "uaa": "xsappname"
        }
      }
    }
  }
```

**Comment by miyasuta** [comment]
@gopalanand333 
I followed the tutorial from the beginning for the second time, but had no luck.
I would appreciate it if you could provide a sample repo with the configurations required for multitenancy, especially for exposing an HTML5 application.

**Comment by gopalanand333** [comment]
@miyasuta 
You can use this branch and check. It is working fine for me : https://github.com/gopalanand333/incidents-app/tree/saas

**Comment by miyasuta** [comment]
@gopalanand333 
Thank you for providing the repo. Unfortunately, the subscribed application is in the same state as before: it is not showing in the HTML apps menu. Although I made small adjustments to mta.yaml to deploy to my subaccount, the basic deployment structure remains untouched.
https://github.com/miyasuta/incidents-app/tree/saas-trial

Can you confirm that the HTML5 app will appear in the consumer's subaccount just after subscribing to the application, before doing any configurations on the subscriber's side?
One note is that I am using a trial account for this tutorial. Can this scenario be tested on a trial account as well?

**Comment by tf484** [comment]
@miyasuta I have the same issue where you able to solve it?

**Comment by gopalanand333** [comment]
@tf484  is your deployment in extension landscape ?

**Comment by tf484** [comment]
my deployment is in cloud foundry, not sure if this answer your question please let me know if you need more details

**Comment by gopalanand333** [comment]
What is the URL of your srv. If the url has something like eu10-004

**Comment by tf484** [comment]
yes this is my URL https://XXX-dev-dev-poc-mt-parts-srv.cfapps.us10.hana.ondemand.com/

**Comment by miyasuta** [comment]
@gopalanand333 
My provider subaccount is in the extension landscape, while my consumer subaccount has not enabled cloud foundry.

![image](https://github.com/user-attachments/assets/18f4cec8-35ef-4d5d-89e7-f1b5f6fb9e15)

![image](https://github.com/user-attachments/assets/93a72fdf-3a26-44c1-8d5c-62dd3d24d01a)

**Comment by tf484** [comment]
this is also my case, my consumer subaccount does not have enable the cloud foundry environment either.

**Comment by gopalanand333** [comment]
Hi @miyasuta there was an issue with workzone it seems which has been resolved sometime back. now you should be able to try this scenario

**Comment by vedant221299** [comment]
Hi @gopalanand333 the issue I described in https://github.com/sap-tutorials/btp-dev-guidance/issues/914 is different than this one.
When I followed the subsequent steps, I encountered the same problem the Application is not visible within the subscriber account>HTML5 Applications.

**Comment by miyasuta** [comment]
Hi @gopalanand333 ,
I have redeployed the app and subscribed to it in a consumer subaccount, but the issue still persists. Therefore, I believe this issue should be re-opened.

**Comment by gopalanand333** [comment]
@miyasuta  can you try this application: https://github.com/cap-js/incidents-app.git 
you will have to configure the domain based on where you are deploying.

**Comment by miyasuta** [comment]
> [@miyasuta](https://github.com/miyasuta) can you try this application: https://github.com/cap-js/incidents-app.git you will have to configure the domain based on where you are deploying.

@gopalanand333 
The main branch in the git repository you shared does not contain mta.yaml. Are you referring to a specific branch?

**Comment by gopalanand333** [comment]
> [@gopalanand333](https://github.com/gopalanand333) The main branch in the git repository you shared does not contain mta.yaml. Are you referring to a specific branch?
The branch is `saas-cdm`

**Comment by miyasuta** [comment]
Hi @gopalanand333 
I'm not an SAP employee. I will check the `saas-cdm` branch. 
By the way, I am using a BTP trial account. Could this be the reason why the app is not visible in the HTML5 app repository of the consumer subaccount?

**Comment by gopalanand333** [comment]
@miyasuta  I suspect the same as it might be due to the trail account. Specially the extension landscape changes service url and that at times causes redirection issues .
Do you have any other non trial account.

**Comment by miyasuta** [comment]
@gopalanand333 
Currently, I don't have any accounts other than the trial account. If I get a chance, I will try on a non-trial account.

**Comment by AgilitaMichail** [comment]
I just have deployed the MTA from the branch [saas-cdm](https://github.com/cap-js/incidents-app/tree/saas-cdm) in one **non-trial** (provider) subaccount and subscribed to the application in another **non-trial** (consumer) subaccount from the same global account and the same region. The application **nsincidents** appears in the list of HTML5 applications in the **provider** subaccount, but does not appear in the **consumer** subaccount.

**Comment by gopalanand333** [comment]
Recently i tested in trial and it is working as expected. So closing the issue.

**Comment by tf484** [comment]
@miyasuta  the issue has been resolved. I opened a case with SAP and after a long investigation, the problem of not fetching  the htlm5 app from the consumer to the subscriber account was that this capability is switched off by feature flag in us10 landscape, they switched it on, and  this solved my issue.

**Comment by AgilitaMichail** [comment]
@tf484 I just have tested once again in eu10. The issue is still there. It seems I have to open a new ticket for eu10. Could you please share the details of your ticket so that the SAP tech support knows what to do?

**Comment by miyasuta** [comment]
@tf484 I also confirmed that the consumer can now see the HTML5 application exposed from the provider account. Thank you very much for raising the ticket and sharing the result.

**Comment by AgilitaMichail** [comment]
I confirm HTML5 apps are exposed in the consumer subaccount in the region **us10**, but not in **eu10**.

**Comment by thisisevanfox** [comment]
> [@tf484](https://github.com/tf484) I just have tested once again in eu10. The issue is still there. It seems I have to open a new ticket for eu10. Could you please share the details of your ticket so that the SAP tech support knows what to do?

Hi @AgilitaMichail, have you already created the ticket? We're facing the same issue.

**Comment by AgilitaMichail** [comment]
@thisisevanfox, yes I did (ticket 317252/2025) and it was successfully resolved by 31 March 2025. In the ticket I provided the links to both provider and consumer subaccounts, so I guess they enabled the feature for our accounts only.

**Comment by thisisevanfox** [comment]
@AgilitaMichail, Thanks for following up! Now it's working on my end as well. I just had to re-subscribe to the application, and everything was fine after that. 👍
